micronaut:
  application:
    name: roleManagement
  server:
    port: 9988
    cors:
      enabled: true
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:5432/role_management
    username: postgres
    password: Pass@1234
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: 'com.management.role'
  show-sql: true
  hibernate:
    ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
